CREATE TABLE `require` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL COMMENT '需求名称',
    summary TEXT NOT NULL COMMENT '需求摘要',
    content LONGTEXT NOT NULL COMMENT '需求原文内容',
    `url` VARCHAR(1024) DEFAULT '' COMMENT '需求文档URL',
    images JSON COMMENT '相关图片URL集合',
    `version` VARCHAR(255) COMMENT '需求版本',
    `owner` VARCHAR(255) COMMENT '需求负责人',
    completeness FLOAT UNSIGNED NOT NULL DEFAULT 0.0 CHECK (completeness BETWEEN 0 AND 20) COMMENT '需求完整性',
    testability FLOAT UNSIGNED NOT NULL DEFAULT 0.0 CHECK (testability BETWEEN 0 AND 30) COMMENT '需求可测性',
    clarity FLOAT UNSIGNED NOT NULL DEFAULT 0.0 CHECK (clarity BETWEEN 0 AND 25) COMMENT '需求完清晰度',
    consistency FLOAT UNSIGNED NOT NULL DEFAULT 0.0 CHECK (consistency BETWEEN 0 AND 15) COMMENT '需求一致性',
    total_score FLOAT UNSIGNED NOT NULL DEFAULT 0.0 CHECK (total_score BETWEEN 0 AND 100)  COMMENT '需求总分',
    issues JSON NOT NULL COMMENT '存储各维度问题明细',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='需求评估结果存储表';